---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: pg-test
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    command: /usr/lib/systemd/systemd
    privileged: true
    tmpfs:
      /run: "rw,size=65536k,mode=755"
      /tmp: "rw,size=65536k,mode=755"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    host_vars:
      pg-test:
        pg_databases:
          - name: testapp_db
            owner: testapp_user
            password: "testpassword123"

lint: |
  set -e
  yamllint .
  ansible-lint
