---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: walg-test
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    command: /usr/lib/systemd/systemd
    privileged: true
    tmpfs:
      /run: "rw,size=65536k,mode=755"
      /tmp: "rw,size=65536k,mode=755"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    host_vars:
      walg-test:
        pg_databases:
          - name: testapp_db
            owner: testapp_user
            password: "testpassword123"
        walg_s3_bucket: "test-bucket"
        walg_s3_endpoint: "http://localhost:9000"
        walg_s3_region: "us-east-1"
        walg_s3_access_key: "minioaccess"
        walg_s3_secret_key: "miniosecret"

lint: |
  set -e
  yamllint .
  ansible-lint
