---
# Private subnet allowed to reach PgBouncer (TCP 6432)
# Override in group_vars/all.yml or host_vars
pg_private_subnet: "10.0.0.0/24"

# Name of the private network interface used by pgbouncer role for listen address
# Override in group_vars/all.yml or host_vars/<host>/vars.yml if NIC name differs
pgbouncer_private_iface: "eth1"
